modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="soup_the_mod"
version="1.0.0"
displayName="Soup: The mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="thoma, MCreator"

[[dependencies.soup_the_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




